import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "../styles/globals.css"; // ✅ Import Global CSS

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], // Adjust as needed
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by ABHI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${josefinSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
